### ISSUE TITLE
Make footer

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia#5] opened 2023-10-04 12:48 UTC
Make a beautiful footer as it looks beautiful

**Comment by samratghosh291** [comment] 2023-10-04 13:42
Go to [https://in.pinterest.com/pin/36028865761543096#imgViewer](url)
Clone it.

**Comment by samratghosh291** [comment] 2023-10-04 13:43
@Baburao-sanivada Thank you for your interest. Happy Coding ❤️

**Comment by Chitresh-code** [comment] 2023-10-04 16:54
Hey @samratghosh291 if the issue is still available please assign it to me.

**Comment by Baburao-sanivada** [comment] 2023-10-05 13:23
Hi @samratghosh291 there is Already a footer present out there
Can I Know How exactly the Footer Should Look Like?

**Closed** 2023-10-19 11:06 UTC
Labels: enhancement, good first issue, hacktoberfest
